### ISSUE TITLE
Mapping rate is very low

### ISSUE THREAD

**Issue by imet-k** [mzytnicki/srnaMapper#1]
from fastq file around 1.6 Gb, it produced only 94 kb sam file. When I opened the file, wiered read names appreared instead of original read names!
This is the header:
@HD     VN:1.6  SO:unsorted
@SQ     SN:NC_004603.1  LN:3288558
@SQ     SN:NC_004605.1  LN:1877212
read_A_0        256     NC_004603.1     1150336 39      6=1X94= *       0       0       GTTCCGATGTTCTTTGTTGTGGTAGAGCGTTTGTTTGATCGCCGTGCTCAAAAAGAAGCGCAGAAAGAACGATCTCAAGAACTCGCTCCAGCAACGGAAAA   FFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF:FFFF:FF   NH:i:1  HI:i:1  IH:i:1  NM:i:1
read_A_1        0       NC_004605.1     615696  40      101=    *       0       0       ACATCGCTTCTTACCTTGCTGCGCTTGATTCATTCGACGGCATCATCTTCACTGGCGGTATTGGCGAGAACTCTATGCCAATTCGTCGTGAAATTCTGAAA   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF::FFFFFFFFFFF:FFFFFFF,FFFFFFFF:FFFFFFFFFF   NH:i:1  HI:i:1  IH:i:1  NM:i:0

notice the name read_A_0 is not a real name. the real name of the read is @A01090:187:HWLCMDRXX:1:2113:16504:26913 1:N:0:GTGGCC

**Comment by mzytnicki** [comment]
This is embarrassing, I rarely check the issues.  Sorry...
I cannot tell you here why the mapping rate is low.  If you want, you can share the files, so I can have a look.
Concerning the read names, it is true that srnamapper modifies them.  I will update the doc!
Thanks, and sorry again for being late to answer!

**Comment by mzytnicki** [comment]
No answer so far...

**Comment by mzytnicki** [comment]
No answer so far...
