### ISSUE TITLE
Incorrect coordinate and/or CIGAR string in output when read has a mismatch at either left or right end

### ISSUE THREAD

**Issue by nnordborg** [mzytnicki/srnaMapper#2]
I have come across an issue where the output in the SAM file is incorrect in the position and/or in the CIGAR string. I have attached a FASTQ file with three reads and the resulting SAM output. 

One read gives an exact match at chr1:65058441 (and also at chr9:4850344). The other reads have a single mismatch, one at the left end and one at the right end. The "right_mismatch" is aligned to chr1:65058440 but it should be at chr1:65058441 (it also aligns to chr9:4850345 which seems correct). The "left_mismatch" aligns to chr1:65058440 with CIGAR: "1I22=". The CIGAR should be "1X22=". The corresponding alignment at chr9:4850345 seems correct.

The command used was: `srnaMapper -r debug.fastq -g hg38_chr_only.fa -o debug.sam`
And for sorting the output: `samtools sort debug.sam -o debug_sorted.sam`

I also include a screenshot from IGV.
[debug.fastq.txt](https://github.com/user-attachments/files/16959593/debug.fastq.txt)
[debug_sorted.sam.txt](https://github.com/user-attachments/files/16959597/debug_sorted.sam.txt)
![debug_igv](https://github.com/user-attachments/assets/816c98c5-606b-454b-b59c-914396b96cc9)

**Comment by mzytnicki** [comment]
Dear @nnordborg,
I thank you very much for your feedback.  I will try to address this problem ASAP.
Matthias.

**Comment by mzytnicki** [comment]
Dear @nnordborg, I updated the code.  It should work on your examples (and mine).
If you use the github repo, could you please confirm?  I will update conda right after.

**Comment by nnordborg** [comment]
I have tested the updated code with both the debug fastq and with real data. I can confirm that the problem seems to be fixed! Thanks a lot for the quick response!

/Nicklas Nordborg

**Comment by mzytnicki** [comment]
Well, thank you very much for mentioning this!
