### ISSUE TITLE
No ARM64 support due to old version of BWA

### ISSUE THREAD

**Issue by martin-g** [mzytnicki/srnaMapper#3]
Hello,

I tried to add ARM64 builds at Bioconda - https://github.com/bioconda/bioconda-recipes/pull/50686, but it fails with:
```
 Libs/bwa/ksw.c:29:10: fatal error: emmintrin.h: No such file or directory
06:38:25 BIOCONDA INFO (OUT)    29 | #include <emmintrin.h>
06:38:25 BIOCONDA INFO (OUT)       |          ^~~~~~~~~~~~~
06:38:25 BIOCONDA INFO (OUT) compilation terminated.
```

Would it be possible to update the copy of BWA to a newer version ? Or use Git submodule ...

BWA supports ARM64 (both Linux and OSX) since [2e603e4581ae0a59c50fac2b67ada37dee30b49d](https://github.com/lh3/bwa/tree/2e603e4581ae0a59c50fac2b67ada37dee30b49d)

Thank you!

**Comment by mzytnicki** [comment]
Most interesting.  I will try.  Thanks for mentioning this!

**Comment by mzytnicki** [comment]
Dear @martin-g,
I tried to update the repo accordingly.  It should now work with bioconda too (hopefully).
Would it be possible to confirm that?
I thank you again,
Matthias.

**Comment by martin-g** [comment]
Hi @mzytnicki !

The ARM64 build passed at Bioconda with https://github.com/bioconda/bioconda-recipes/pull/50699
And the binaries are available - https://anaconda.org/search?q=srnamapper

Thank you for the quick resolution!
