### ISSUE TITLE
srnaMapper_keep_original_read_name

### ISSUE THREAD

**Issue by mbiotMP** [mzytnicki/srnaMapper#4]
Dear creator of srnaMapper,

Thank you for the creation of this tool. I would like to test it and compare the alignment result with other tools. Therefore I would like to conserve the original read name from the fastq file. However after aligning with your tool, the name are 'read_A_0, read_A_1'. 
I did not find out how to do it, would you please highlight me on this?

Thank you very much and best regard,
Mathilde

**Comment by mzytnicki** [comment]
Dear Mathilde,
I thank you very much for your interest in srnaMapper.
Actually, it seems to me that you are using a (quite) old version of the tool.  Would it be possible for you to check that you have the last version?  I think that the conda repo is also up to date.
If so, does that work?
Best regards,
Matthias.

**Comment by mbiotMP** [comment]
Thank you for your answer. I installed it with conda and I have the following version 1.0.7.

**Comment by mzytnicki** [comment]
My! Last version in 1.0.10, on GitHub (this repo) and on [bioconda](https://bioconda.github.io/recipes/srnamapper/README.html). Is there something wrong?

**Comment by mbiotMP** [comment]
Alright, I just uninstall and reinstall the tool with the command:
conda install -c bioconda srnamapper

and it install the 1.0.7.

Thank you

**Comment by mzytnicki** [comment]
D'oh!  This is something wrong, probably in the dependencies, probably with conda.  Would it be possible to install it from the repo?  Do you use Linux?  I can assist you here.

**Comment by mzytnicki** [comment]
By the way, if you have `mamba` installed, you could give it a try: `mamba update srnamapper`

**Comment by mbiotMP** [comment]
I do not have mamba, and yes I am on linux.
What do you recommend then?

Thank you so much.

**Comment by mzytnicki** [comment]
You can install `mamba` following instructions on https://github.com/conda-forge/miniforge
Installing `srnaMapper` is explained on the `README`:

    # Go to a suitable directory
    git clone --recurse-submodules https://github.com/mzytnicki/srnaMapper.git
    cd srnaMapper
    make
    # You should see an executable file srnaMapper

Does that work?

**Comment by mbiotMP** [comment]
This what I did knowing that I have Anaconda3 install. 
I install miniforge: 
bash Miniforge3-Linux-x86_64.sh
/home/mathilde/miniforge3/bin/mamba install srnamapper

I got the following error:
Looking for: ['srnamapper']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
pkgs/r/linux-64                                               No change
pkgs/main/linux-64                                            No change
pkgs/main/noarch                                              No change
pkgs/r/noarch                                                 No change

Pinned packages:
  - python 3.12.*


Could not solve for environment specs
The following package could not be installed
└─ srnamapper does not exist (perhaps a typo or a missing channel).


I tried also by deactivating conda from anaconda and get the same thing. Also I checked the version of python and it return me that it is ok.

Thank you for your help

**Comment by mzytnicki** [comment]
I see.  I am no expert in `conda`.  What about this:

    /home/mathilde/miniforge3/bin/mamba install -c bioconda srnamapper

**Comment by mbiotMP** [comment]
Yalaaa! It worked! but the version is 1.0.8.

I did mamba update srnamapper and it gived me the same error as before.

**Comment by mbiotMP** [comment]
gave*

**Comment by mzytnicki** [comment]
Oops!  That should be the last version.  I forgot to update the code. I will do it.
Now, are your read names here in the SAM file?
Thanks.

**Comment by mbiotMP** [comment]
Oh yeah! Thank you so much for all!
Have a nice day,
Mathilde

**Comment by mzytnicki** [comment]
Great, thank you!
